Uh, pip, what ya doin' buddy?
It's not that coverage isn't on %PATH%, it never even gets installed.
Because

    ERROR: Could not open requirements file: [Errno 2] No such file or
    directory: 'constraints'

only why does the .txt get stripped off at the end????  pip, buddy,
what?

I've no idea why I think adding a space after the -c might help.