Fix error when using remote task list
The error was

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/gtimelog/main.py", line 979, in tasks_downloaded
        content.decode('UTF-8', 'replace').replace('\n', '\n  '))
    AttributeError: 'str' object has no attribute 'decode'

because apparently Soap gives us a unicode string (on Python 3) instead
of bytes?

I've tested the new code on both Python 2 and 3, on a URL that responds
with Content-Type: text/plain; charset=utf-8 and returns non-ASCII data.

Fixes #153.